from pathlib import Path

BASE_DIR = Path(__file__).parent.parent/"fastapi_results"
OUTPUTS_DIR = BASE_DIR / "outputs"
OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)
INFERENCE_DIR = BASE_DIR / "inference"
INFERENCE_DIR.mkdir(parents=True, exist_ok=True)
INFERENCE_DATA_PATH = INFERENCE_DIR / "inference_data.csv"
MERGED_CSV_PATH = OUTPUTS_DIR / "merged_data.csv"
TRANSFORM_STAGE1= OUTPUTS_DIR / "transformed_stage1.csv"
X_TRAIN_PATH = OUTPUTS_DIR / "X_train.csv"
X_TEST_PATH = OUTPUTS_DIR / "X_test.csv"
Y_TRAIN_PATH = OUTPUTS_DIR / "y_train.csv"
Y_TEST_PATH = OUTPUTS_DIR / "y_test.csv"
METADATA_PATH = OUTPUTS_DIR / "metadata.json"
X_TRAIN_TRANSFOMED2_PATH = OUTPUTS_DIR / "X_train_transformed_stage2.csv"
X_TEST_TRANSFOMED2_PATH = OUTPUTS_DIR / "X_test_transformed_stage2.csv"
X_TRAIN_TRANSFOMED3_PATH = OUTPUTS_DIR / "X_train_transformed_stage3.csv"
X_TEST_TRANSFORMED3_PATH = OUTPUTS_DIR / "X_test_transformed_stage3.csv"
ENCODER_PATH = OUTPUTS_DIR / "encoder.joblib"
SCALER_PATH = OUTPUTS_DIR / "scaler.joblib"
SELECTED_COLUMNS_PATH = OUTPUTS_DIR / "selected_columns.joblib"
DF_INFERENCE_TRANSFORMED3_PATH = OUTPUTS_DIR / "df_inference_transformed_stage3.csv"
X_TRAIN_BALANCED_PATH = OUTPUTS_DIR / "X_train_balanced.csv"
Y_TRAIN_BALANCED_PATH = OUTPUTS_DIR / "y_train_balanced.csv"
INFERENCE_RESULT = OUTPUTS_DIR / "inference_results.json"
MODEL_PATH = OUTPUTS_DIR / "model.joblib"
EVALUATION_METRICS_PATH = OUTPUTS_DIR / "evaluation_metrics.json"
CARDS_PATH=BASE_DIR.parent/"raw_data"/"data"/"8"/"sd254_cards.csv"
USERS_PATH=BASE_DIR.parent/"raw_data"/"data"/"8"/"sd254_users.csv"
TRANSACTIONS_PATH=BASE_DIR.parent/"raw_data"/"data"/"8"/"User0_credit_card_transactions.csv"