name: GCP Clouod Run Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - milad/sharply-16
env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID_SHARPLY_PROD }}
  REGISTRY_URL: us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID_SHARPLY_PROD }}/${{ vars.GCP_PROJECT_ID_SHARPLY_PROD }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_SHARPLY_PROD }}
  IMAGE_NAME: api-app
  GCP_SA_KEY_FILE_NAME: project_sa_key.json
  IMAGE_TAG: ${{vars.REGION_URL}}/${{ vars.GCP_PROJECT_ID_SHARPLY_PROD }}/${{ vars.GCP_PROJECT_ID_SHARPLY_PROD }}/api-app:${{ github.sha }}
  BUILD_VERSION: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
 

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY_SHARPLY_PROD }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name: 'Use gcloud CLI'
      run: |
        gcloud info
        gcloud auth list

    - name: 'Authenticate Service Account'
      run: |
        gcloud config set project $GCP_PROJECT_ID
        echo $GCP_SA_KEY > ${HOME}/$GCP_SA_KEY_FILE_NAME
        gcloud auth activate-service-account --key-file=${HOME}/$GCP_SA_KEY_FILE_NAME
        gcloud auth configure-docker ${REGION_URL} --quiet

    - name: 'Build and Push Image'
      run: |
        DIR_NAME="ml_api"

        cd ./$DIR_NAME
        docker build -t ${{ env.IMAGE_TAG }} -f Dockerfile .
        docker tag $REGISTRY_URL/$IMAGE_NAME:${{ github.sha }} $REGISTRY_URL/$IMAGE_NAME:latest
        docker push $REGISTRY_URL/$IMAGE_NAME:${{ github.sha }}
        docker push $REGISTRY_URL/$IMAGE_NAME:latest

    - name: 'Deploy Docker Image to Cloud Run'
      run: |
        gcloud run deploy $IMAGE_NAME \
        --image $REGISTRY_URL/$IMAGE_NAME:${{ github.sha }} \
        --service-account project@$GCP_PROJECT_ID.iam.gserviceaccount.com \
        --region ${{ vars.REGION }} \
        --port 80 \
        --timeout 10m \
        --execution-environment gen2 \
        --allow-unauthenticated \
        --max-instances 1 \
        --min-instances 0 \
        --memory '512Mi' \
        --cpu 1
